CREATE TABLE Employee(
	Fname VARCHAR(15) NOT NULL,
    Minit CHAR,
    Lname VARCHAR(15) NOT NULL,
	Ssn INT NOT NULL,
	Bdate DATE,
    Address VARCHAR(25),
    Salary INT NOT NULL,
    Super_ssn INT,
    Dno INT DEFAULT 21,
    PRIMARY KEY(Ssn),
	FOREIGN KEY(Super_ssn) REFERENCES EMPLOYEE(Ssn)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE DEPARTMENT(
	Dname VARCHAR(20),
    Dnumber INT CHECK(Dnumber > 0 AND Dnumber <= 21),
    Mgr_ssn INT DEFAULT 99999,
    Mgr_start_date DATE,
    PRIMARY KEY(Dnumber),
	UNIQUE(Dname)
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_Dept_Mgr
FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_Emp_Dept
FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber)
ON UPDATE CASCADE ON DELETE SET NULL;